export const ActionTypes = {
  USER: {
    USER_LOGIN_REQUEST: "USER.USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "USER.USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER.USER_LOGIN_FAILURE",
    USER_LOGOUT_REQUEST: "USER.USER_LOGOUT_REQUEST",
    USER_LOGOUT_SUCCESS: "USER.USER_LOGOUT_SUCCESS",
    USER_LOGOUT_FAILURE: "USER.USER_LOGOUT_FAILURE",
  },
  GITHUB: {
    GITHUB_GET_REPOS_REQUEST: "GITHUB.GITHUB_GET_REPOS_REQUEST",
    GITHUB_GET_REPOS_SUCCESS: "GITHUB.GITHUB_GET_REPOS_SUCCESS",
    GITHUB_GET_REPOS_FAILURE: "GITHUB.GITHUB_GET_REPOS_FAILURE",
  },
  ALERT: {
    SHOW_ALERT: "ALERT.SHOW_ALERT",
    HIDE_ALERT: "ALERT.HIDE_ALERT",
  },
  VIEWS: {
    ALL_DB: {
      ALL_DB_LOAD_REQUEST: "VIEWS.ALL_DB.ALL_DB_LOAD_REQUEST",
      ALL_DB_LOAD_SUCESS: "VIEWS.ALL_DB.ALL_DB_LOAD_SUCESS",
      ALL_DB_LOAD_FAILURE: "VIEWS.ALL_DB.ALL_DB_LOAD_FAILURE",
      ALL_DB_TOGGLE_GRAPH_VIEW: "VIEWS.ALL_DB.ALL_DB_TOGGLE_GRAPH_VIEW",
      ALL_DB_STORED_PROC_SELECTION_CHANGED: "VIEWS.ALL_DB.ALL_DB_STORED_PROC_SELECTION_CHANGED",
      ALL_DB_TABLE_SELECTION_CHANGED: "VIEWS.ALL_DB.ALL_DB_TABLE_SELECTION_CHANGED",
      ALL_DB_RELATION_SELECTION_CHANGED: "VIEWS.ALL_DB.ALL_DB_RELATION_SELECTION_CHANGED",
      ALL_DB_RELATION_TYPES_SELECTION_CHANGED: "VIEWS.ALL_DB.ALL_DB_RELATION_TYPES_SELECTION_CHANGED",
      ALL_DB_REMOVE_NODES_REQUESTED: "VIEWS.ALL_DB.ALL_DB_REMOVE_NODES_REQUESTED",
      ALL_DB_USER_SELECTION_CHANGED: "VIEWS.ALL_DB.ALL_DB_USER_SELECTION_CHANGED",
      ALL_DB_TEAM_SELECTION_CHANGED: "VIEWS.ALL_DB.ALL_DB_TEAM_SELECTION_CHANGED",
    }
  }
}

export const XHR = {
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
};
